name: rpgm_translator
description: RPG Maker Translator for Android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.0
  file_picker: ^6.1.1
  archive: ^3.3.7
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode-Regular.ttf
